language: php

php:
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit -d memory_limit=1024M

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true